[package]
name = "awe-product-core-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
awe-driverd = { path = "../../services/driverd" }
awe-appd = { path = "../../services/appd" }
awe-update = { path = "../../services/update" }
awe-ayui = { path = "../../services/ayui" }
aweos-kernel = { path = "../../kernel" }
