[workspace]
members = [
    "boot/protocol",
    "boot/aweloader",
    "kernel",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
awe-boot-protocol = { path = "boot/protocol" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"
codegen-units = 1
