[workspace]
members = [
    "boot/protocol",
    "boot/aweloader",
    "kernel",
    "kernel-bin",
    "services/driverd",
    "services/initd",
    "services/identityd",
    "services/awosa",
    "services/appd",
    "services/update",
    "tools/aweosa-builder",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
awe-boot-protocol = { path = "boot/protocol" }
awe-driverd = { path = "services/driverd" }
awe-initd = { path = "services/initd" }
awe-identityd = { path = "services/identityd" }
awe-awosa = { path = "services/awosa" }
awe-appd = { path = "services/appd" }
awe-update = { path = "services/update" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"
codegen-units = 1
