[workspace]
members = [
    "boot/protocol",
    "boot/aweloader",
    "boot/arm",
    "boot/riscv",
    "kernel",
    "kernel-bin",
    "services/nexus",
    "services/netd",
    "services/storaged",
    "services/securityd",
    "services/driverd",
    "services/initd",
    "services/identityd",
    "services/appd",
    "services/update",
    "services/platformd",
    "services/ayui",
    "apps/terminal",
    "apps/filemanager",
    "apps/settings",
    "apps/calculator",
    "apps/sysmon",
    "apps/texteditor",
    "apps/pkgcenter",
    "apps/recovery",
    "tools/awescript",
    "tools/awe-cli",
    "tools/aosin-gui",
    "tests/product-core",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
awe-boot-protocol = { path = "boot/protocol" }
awe-nexus = { path = "services/nexus" }
awe-netd = { path = "services/netd" }
awe-storaged = { path = "services/storaged" }
awe-securityd = { path = "services/securityd" }
awe-driverd = { path = "services/driverd" }
awe-initd = { path = "services/initd" }
awe-identityd = { path = "services/identityd" }
awe-appd = { path = "services/appd" }
awe-update = { path = "services/update" }
awe-platformd = { path = "services/platformd" }
awe-ayui = { path = "services/ayui" }
awe-script = { path = "tools/awescript" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"
codegen-units = 1
