#![no_std]
use super::contract::DeviceContract;
use super::core::{AdapterState,AndroidDriverAdapter,CoreError,DriverAdapter,DriverSlot,HardwareAbstraction,HardwareInfo};
use super::universal::{DriverAbi,DriverOs};
pub struct AndroidLayer<A>{pub slot:DriverSlot<A>}
impl<A:AndroidDriverAdapter>AndroidLayer<A>{
 pub const fn new(adapter:A)->Self{Self{slot:DriverSlot::new(adapter)}}
 pub fn validate(&self,hw:&HardwareInfo)->Result<(),CoreError>{let id=self.slot.adapter.identity();if id.os!=DriverOs::Android||id.abi!=DriverAbi::AndroidHal{return Err(CoreError::UnsupportedAbi)}if !id.signed{return Err(CoreError::PolicyDenied)}let api=self.slot.adapter.android_hal_version();if id.api_version==0||api==0||api>u32::from(u16::MAX)||id.api_version!=api as u16{return Err(CoreError::InvalidRequest)}let name=self.slot.adapter.android_interface_name();if name.len()<3||!name.as_bytes().iter().any(|b|*b==b'/'){return Err(CoreError::InvalidRequest)}if !id.matches(hw)||!hw.valid()||hw.irq==u32::MAX{return Err(CoreError::InvalidDevice)}Ok(())}
 pub fn validate_contract<const M:usize>(&self,hw:&HardwareInfo,contract:&DeviceContract<M>)->Result<(),CoreError>{self.validate(hw)?;if !contract.valid(){return Err(CoreError::InvalidRequest)}if contract.vendor!=hw.id.vendor||contract.device!=hw.id.device||contract.class_code!=hw.id.class{return Err(CoreError::InvalidDevice)}let end=hw.mmio_base.checked_add(hw.mmio_length).ok_or(CoreError::MmioDenied)?;if !contract.allows_mmio_range(hw.mmio_base,hw.mmio_length)||contract.mmio.iter().flatten().any(|r|r.base.checked_add(r.length).is_none()||r.base<hw.mmio_base||r.base.checked_add(r.length).unwrap()>end){return Err(CoreError::MmioDenied)}if hw.dma_bits<32||hw.dma_bits>contract.dma.address_bits{return Err(CoreError::DmaDenied)}Ok(())}
 pub fn can_probe(&self,hw:&HardwareInfo)->bool{self.validate(hw).is_ok()&&self.slot.state==AdapterState::New}
 pub fn probe(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{self.validate(hw)?;if self.slot.state!=AdapterState::New{return Err(CoreError::NotBound)}self.slot.adapter.probe(hw).map_err(|_|CoreError::ProbeFailed)?;self.slot.state=AdapterState::Probed;Ok(())}
 pub fn start(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{self.validate(hw)?;if self.slot.state!=AdapterState::Probed&&self.slot.state!=AdapterState::Stopped{return Err(CoreError::NotBound)}self.slot.adapter.start(hw).map_err(|_|CoreError::StartFailed)?;self.slot.state=AdapterState::Running;Ok(())}
 pub fn stop(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.adapter.stop(hw).map_err(|_|CoreError::PolicyDenied)?;self.slot.state=AdapterState::Stopped;Ok(())}
 pub fn remove(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{if self.slot.state==AdapterState::Running{return Err(CoreError::PolicyDenied)}if self.slot.state==AdapterState::Removed{return Err(CoreError::NotBound)}self.slot.adapter.remove(hw).map_err(|_|CoreError::PolicyDenied)?;self.slot.state=AdapterState::Removed;Ok(())}
 pub fn irq_ack<H:HardwareAbstraction>(&mut self,hw:&HardwareInfo,hal:&mut H)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}if hw.irq==u32::MAX{return Err(CoreError::IrqDenied)}hal.irq_ack(hw)}
 pub fn shutdown<H:HardwareAbstraction>(&mut self,hw:&HardwareInfo,hal:&mut H)->Result<(),CoreError>{if self.slot.state==AdapterState::Running{self.irq_ack(hw,hal)?;self.stop(hw)?;}if self.slot.state==AdapterState::Stopped||self.slot.state==AdapterState::Probed{self.remove(hw)?;Ok(())}else{Err(CoreError::NotBound)}}
 pub fn recover<H:HardwareAbstraction>(&mut self,hw:&HardwareInfo,hal:&mut H)->Result<(),CoreError>{self.validate(hw)?;match self.slot.state{AdapterState::New=>{self.probe(hw)?;self.start(hw)?},AdapterState::Probed=>self.start(hw)?,AdapterState::Running=>{self.irq_ack(hw,hal)?;self.stop(hw)?;self.start(hw)?},AdapterState::Stopped=>self.start(hw)?,AdapterState::Removed=>return Err(CoreError::NotBound)}Ok(())}
 pub fn io_cycle<H:HardwareAbstraction>(&mut self,hw:&HardwareInfo,hal:&mut H,offset:u64,value:u32,dma_bytes:u64,address_bits:u8)->Result<u32,CoreError>{if self.slot.state==AdapterState::New{self.probe(hw)?}if self.slot.state==AdapterState::Probed{self.start(hw)?}self.slot.mmio_write32(hw,hal,offset,value)?;let read=self.slot.mmio_read32(hw,hal,offset)?;self.slot.dma_submit(hw,hal,dma_bytes,address_bits)?;Ok(read)}
 pub fn io_cycle_contract<H:HardwareAbstraction,const M:usize>(&mut self,hw:&HardwareInfo,contract:&DeviceContract<M>,hal:&mut H,offset:u64,value:u32,dma_bytes:u64,address_bits:u8)->Result<u32,CoreError>{self.validate_contract(hw,contract)?;if self.slot.state==AdapterState::New{self.probe(hw)?}if self.slot.state==AdapterState::Probed{self.start(hw)?}self.slot.mmio_write32_contract_base(hw,contract,hal,offset,value)?;let read=self.slot.mmio_read32_contract_base(hw,contract,hal,offset)?;self.slot.dma_submit_contract(hw,contract,hal,dma_bytes,address_bits)?;Ok(read)}
}
#[cfg(test)]mod tests{use super::*;use super::super::bus::DeviceId;struct Mock{api:u32,name:&'static str,os:DriverOs,abi:DriverAbi,vendor:u16,device:u16,signed:bool}impl DriverAdapter for Mock{fn identity(&self)->super::super::core::DriverIdentity{super::super::core::DriverIdentity{os:self.os,abi:self.abi,api_version:self.api as u16,vendor:self.vendor,device:self.device,signed:self.signed}}fn probe(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}fn start(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}fn stop(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}fn remove(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}}impl AndroidDriverAdapter for Mock{fn android_hal_version(&self)->u32{self.api}fn android_interface_name(&self)->&'static str{self.name}}struct Hal{last:u32,acks:u32}impl HardwareAbstraction for Hal{fn mmio_read32(&self,_:&HardwareInfo,_:u64)->Result<u32,CoreError>{Ok(self.last)}fn mmio_write32(&mut self,_:&HardwareInfo,_:u64,value:u32)->Result<(),CoreError>{self.last=value;Ok(())}fn irq_ack(&mut self,_:&HardwareInfo)->Result<(),CoreError>{self.acks+=1;Ok(())}fn dma_submit(&mut self,_:&HardwareInfo,_:u64)->Result<(),CoreError>{Ok(())}}fn hw()->HardwareInfo{HardwareInfo{id:DeviceId{vendor:1,device:2,class:0,revision:1},mmio_base:0x1000,mmio_length:0x100,irq:5,dma_bits:64}}fn contract()->DeviceContract<1>{DeviceContract{vendor:1,device:2,class_code:0,mmio:[Some(super::super::contract::MmioRegion{base:0x1000,length:0x100})],interrupt:super::super::contract::InterruptMode::Msi,dma:super::super::contract::DmaPolicy{max_bytes:64,address_bits:64,coherent:true}}}
fn layer()->AndroidLayer<Mock>{AndroidLayer::new(Mock{api:7,name:"vendor/awe-hal",os:DriverOs::Android,abi:DriverAbi::AndroidHal,vendor:1,device:2,signed:true})}
#[test]fn signed_contract_io_cycle(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.io_cycle_contract(&hw(),&contract(),&mut h,0x10,0x12345678,16,32),Ok(0x12345678));assert_eq!(x.slot.state,AdapterState::Running)}
#[test]fn irq_ack_requires_running(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.irq_ack(&hw(),&mut h),Err(CoreError::NotBound));}
#[test]fn shutdown_acknowledges_and_removes(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.io_cycle_contract(&hw(),&contract(),&mut h,0x10,7,16,32),Ok(7));assert_eq!(x.shutdown(&hw(),&mut h),Ok(()));assert_eq!(h.acks,1);assert_eq!(x.slot.state,AdapterState::Removed)}
#[test]fn recovery_restarts_running_hal(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.io_cycle_contract(&hw(),&contract(),&mut h,0x10,7,16,32),Ok(7));assert_eq!(x.recover(&hw(),&mut h),Ok(()));assert_eq!(h.acks,1);assert_eq!(x.slot.state,AdapterState::Running)}
#[test]fn recovery_starts_stopped_hal(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.io_cycle_contract(&hw(),&contract(),&mut h,0x10,7,16,32),Ok(7));assert_eq!(x.stop(&hw()),Ok(()));assert_eq!(x.recover(&hw(),&mut h),Ok(()));assert_eq!(x.slot.state,AdapterState::Running)}
#[test]fn unsigned_hal_is_rejected(){let x=AndroidLayer::new(Mock{api:7,name:"vendor/awe-hal",os:DriverOs::Android,abi:DriverAbi::AndroidHal,vendor:1,device:2,signed:false});assert_eq!(x.validate(&hw()),Err(CoreError::PolicyDenied));}
#[test]fn bad_contract_range_is_rejected(){let mut x=layer();let mut h=Hal{last:0,acks:0};assert_eq!(x.io_cycle_contract(&hw(),&contract(),&mut h,0x100,1,16,32),Err(CoreError::MmioDenied));}}
