#![no_std]

#[repr(C)] #[derive(Clone,Copy,PartialEq,Eq,Debug)] pub struct MmioRegion{pub base:u64,pub length:u64}
impl MmioRegion{pub const fn end(&self)->Option<u64>{self.base.checked_add(self.length)} pub const fn contains(&self,address:u64)->bool{match self.end(){Some(end)=>address>=self.base&&address<end,None=>false}} pub const fn contains_range(&self,base:u64,length:u64)->bool{if length==0{return false}match base.checked_add(length){Some(end)=>match self.end(){Some(region_end)=>base>=self.base&&end<=region_end,None=>false},None=>false}} pub const fn overlaps(&self,other:&Self)->bool{ranges_overlap(self.base,self.length,other.base,other.length)} }
#[repr(u8)] #[derive(Clone,Copy,PartialEq,Eq,Debug)] pub enum InterruptMode{None=0,Legacy=1,Msi=2,MsiX=3}
#[repr(C)] #[derive(Clone,Copy,PartialEq,Eq,Debug)] pub struct DmaPolicy{pub max_bytes:u64,pub address_bits:u8,pub coherent:bool}
#[repr(C)] #[derive(Clone,Copy,PartialEq,Eq,Debug)] pub struct DeviceContract<const M:usize>{pub vendor:u16,pub device:u16,pub class_code:u32,pub mmio:[Option<MmioRegion>;M],pub interrupt:InterruptMode,pub dma:DmaPolicy}
impl<const M:usize> DeviceContract<M>{
 pub const fn valid(&self)->bool{if self.vendor==0||self.vendor==0xffff||self.device==0||self.device==0xffff||self.dma.max_bytes==0||self.dma.address_bits<32||self.dma.address_bits>64{return false} let mut i=0;while i<M{if let Some(r)=self.mmio[i]{if r.length==0||r.end().is_none(){return false}let mut j=0;while j<i{if let Some(other)=self.mmio[j]{if r.overlaps(&other){return false}}j+=1}}i+=1}true}
 pub const fn allows_mmio(&self,address:u64)->bool{let mut i=0;while i<M{if let Some(r)=self.mmio[i]{if r.contains(address){return true}}i+=1}false}
 pub const fn allows_mmio_range(&self,base:u64,length:u64)->bool{let mut i=0;while i<M{if let Some(r)=self.mmio[i]{if r.contains_range(base,length){return true}}i+=1}false}
 pub const fn allows_dma(&self,bytes:u64,address_bits:u8)->bool{bytes!=0&&bytes<=self.dma.max_bytes&&address_bits>=32&&address_bits<=self.dma.address_bits}
}
const fn ranges_overlap(a:u64,al:u64,b:u64,bl:u64)->bool{match(a.checked_add(al),b.checked_add(bl)){(Some(ae),Some(be))=>a<be&&b<ae,_=>true}}
#[cfg(test)]mod tests{use super::*;fn c()->DeviceContract<2>{DeviceContract{vendor:1,device:2,class_code:0,mmio:[Some(MmioRegion{base:0x1000,length:0x1000}),None],interrupt:InterruptMode::Msi,dma:DmaPolicy{max_bytes:4096,address_bits:48,coherent:true}}}#[test]fn mmio_range_is_overflow_safe(){let r=MmioRegion{base:0x1000,length:0x100};assert!(r.contains(0x1080));assert!(!r.contains(0x1100));assert!(!MmioRegion{base:u64::MAX,length:2}.contains(u64::MAX))}#[test]fn range_and_dma_policies_are_enforced(){let x=c();assert!(x.valid());assert!(x.allows_mmio_range(0x1100,0x100));assert!(!x.allows_mmio_range(0x1f00,0x200));assert!(x.allows_dma(4096,48));assert!(!x.allows_dma(4097,48));assert!(!x.allows_dma(1024,64))}#[test]fn invalid_device_ids_are_rejected(){let mut x=c();x.vendor=0xffff;assert!(!x.valid())}#[test]fn overlapping_mmio_is_rejected(){let mut x=c();x.mmio[1]=Some(MmioRegion{base:0x1800,length:0x100});assert!(!x.valid())}#[test]fn adjacent_mmio_is_allowed(){let mut x=c();x.mmio[1]=Some(MmioRegion{base:0x2000,length:0x100});assert!(x.valid())}#[test]fn invalid_mmio_and_dma_width_are_rejected(){let mut a=c();a.mmio[0]=Some(MmioRegion{base:0x1000,length:0});assert!(!a.valid());let mut b=c();b.dma.address_bits=65;assert!(!b.valid())}}
