#![no_std]
use super::bus::DeviceId;
use super::contract::{DeviceContract,InterruptMode};
use super::universal::{DriverAbi,DriverAction,DriverOs};
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub enum CoreError{InvalidDevice,UnsupportedAbi,InvalidRequest,PolicyDenied,ProbeFailed,StartFailed,NotBound,MmioDenied,DmaDenied,IrqDenied}
#[repr(C)]#[derive(Clone,Copy)]pub struct HardwareInfo{pub id:DeviceId,pub mmio_base:u64,pub mmio_length:u64,pub irq:u32,pub dma_bits:u8}
impl HardwareInfo{pub const fn valid(&self)->bool{self.id.vendor!=0&&self.id.vendor!=0xffff&&self.id.device!=0&&self.id.device!=0xffff&&self.mmio_length!=0&&self.dma_bits>=32&&self.dma_bits<=64&&self.mmio_base.checked_add(self.mmio_length).is_some()}pub const fn mmio_contains(&self,offset:u64,width:u64)->bool{width!=0&&offset<=self.mmio_length&&width<=self.mmio_length-offset}}
#[repr(C)]#[derive(Clone,Copy)]pub struct DriverIdentity{pub os:DriverOs,pub abi:DriverAbi,pub api_version:u16,pub vendor:u16,pub device:u16,pub signed:bool}
impl DriverIdentity{pub const fn matches(&self,hw:&HardwareInfo)->bool{self.vendor==hw.id.vendor&&self.device==hw.id.device&&self.signed&&self.api_version!=0}}
pub trait HardwareAbstraction{fn mmio_read32(&self,hw:&HardwareInfo,offset:u64)->Result<u32,CoreError>;fn mmio_write32(&mut self,hw:&HardwareInfo,offset:u64,value:u32)->Result<(),CoreError>;fn irq_ack(&mut self,hw:&HardwareInfo)->Result<(),CoreError>;fn dma_submit(&mut self,hw:&HardwareInfo,bytes:u64)->Result<(),CoreError>}
pub trait DriverAdapter{fn identity(&self)->DriverIdentity;fn probe(&mut self,hw:&HardwareInfo)->Result<(),CoreError>;fn start(&mut self,hw:&HardwareInfo)->Result<(),CoreError>;fn stop(&mut self,hw:&HardwareInfo)->Result<(),CoreError>;fn remove(&mut self,hw:&HardwareInfo)->Result<(),CoreError>}
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub enum AdapterState{New,Probed,Running,Stopped,Removed}
pub struct DriverSlot<A>{pub adapter:A,pub state:AdapterState}
impl<A:DriverAdapter>DriverSlot<A>{pub const fn new(adapter:A)->Self{Self{adapter,state:AdapterState::New}}pub fn dispatch<H:HardwareAbstraction>(&mut self,action:DriverAction,hw:&HardwareInfo,hal:&mut H)->Result<(),CoreError>{if !hw.valid()||!self.adapter.identity().matches(hw){return Err(CoreError::InvalidDevice)}match action{DriverAction::Probe=>{self.adapter.probe(hw)?;self.state=AdapterState::Probed;Ok(())},DriverAction::Start=>{if self.state!=AdapterState::Probed&&self.state!=AdapterState::Stopped{return Err(CoreError::NotBound)}self.adapter.start(hw)?;self.state=AdapterState::Running;Ok(())},DriverAction::Stop=>{if self.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.adapter.stop(hw)?;self.state=AdapterState::Stopped;Ok(())},DriverAction::Remove=>{if self.state==AdapterState::Running{return Err(CoreError::PolicyDenied)}self.adapter.remove(hw)?;self.state=AdapterState::Removed;Ok(())},DriverAction::Bind=>Err(CoreError::InvalidRequest)}}pub fn mmio_read32(&self,hw:&HardwareInfo,hal:&impl HardwareAbstraction,offset:u64)->Result<u32,CoreError>{if self.state!=AdapterState::Running{return Err(CoreError::NotBound)}if !hw.mmio_contains(offset,4){return Err(CoreError::MmioDenied)}hal.mmio_read32(hw,offset)}pub fn mmio_write32(&self,hw:&HardwareInfo,hal:&mut impl HardwareAbstraction,offset:u64,value:u32)->Result<(),CoreError>{if self.state!=AdapterState::Running{return Err(CoreError::NotBound)}if !hw.mmio_contains(offset,4){return Err(CoreError::MmioDenied)}hal.mmio_write32(hw,offset,value)}pub fn irq_ack(&self,hw:&HardwareInfo,hal:&mut impl HardwareAbstraction)->Result<(),CoreError>{if self.state!=AdapterState::Running{return Err(CoreError::NotBound)}if hw.irq==u32::MAX{return Err(CoreError::IrqDenied)}hal.irq_ack(hw)}pub fn dma_submit(&self,hw:&HardwareInfo,hal:&mut impl HardwareAbstraction,bytes:u64,address_bits:u8)->Result<(),CoreError>{if self.state!=AdapterState::Running{return Err(CoreError::NotBound)}if bytes==0||bytes>u64::from(hw.mmio_length)||address_bits<32||address_bits>hw.dma_bits{return Err(CoreError::DmaDenied)}hal.dma_submit(hw,bytes)}pub fn dma_submit_contract<const M:usize>(&self,hw:&HardwareInfo,contract:&DeviceContract<M>,hal:&mut impl HardwareAbstraction,bytes:u64,address_bits:u8)->Result<(),CoreError>{if self.state!=AdapterState::Running||!contract.valid()||contract.vendor!=hw.id.vendor||contract.device!=hw.id.device{return Err(CoreError::DmaDenied)}if !contract.allows_dma(bytes,address_bits){return Err(CoreError::DmaDenied)}hal.dma_submit(hw,bytes)}pub fn irq_ack_contract<const M:usize>(&self,hw:&HardwareInfo,contract:&DeviceContract<M>,mode:InterruptMode,hal:&mut impl HardwareAbstraction)->Result<(),CoreError>{if self.state!=AdapterState::Running||!contract.valid()||contract.vendor!=hw.id.vendor||contract.device!=hw.id.device||!contract.allows_interrupt(mode){return Err(CoreError::IrqDenied)}hal.irq_ack(hw)}}
pub trait LinuxDriverAdapter:DriverAdapter{fn linux_api_version(&self)->u32;fn linux_module_name(&self)->&'static str}pub trait WindowsDriverAdapter:DriverAdapter{fn windows_api_version(&self)->u32;fn windows_driver_name(&self)->&'static str}pub trait AndroidDriverAdapter:DriverAdapter{fn android_hal_version(&self)->u32;fn android_interface_name(&self)->&'static str}
