#![no_std]

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct VirtioFeatures(pub u64);
impl VirtioFeatures { pub const VERSION_1:Self=Self(1<<32);pub const ACCESS_PLATFORM:Self=Self(1<<33);pub const RING_INDIRECT_DESC:Self=Self(1<<28);pub const RING_EVENT_IDX:Self=Self(1<<29);pub const RING_PACKED:Self=Self(1<<34);pub const fn contains(self,o:Self)->bool{(self.0&o.0)==o.0}pub const fn intersection(self,o:Self)->Self{Self(self.0&o.0)} }

pub const DESC_NEXT:u16=1;
pub const DESC_WRITE:u16=2;
pub const DESC_INDIRECT:u16=4;
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub enum VirtioError{MissingVersion,AlreadyReady,QueueCountZero,QueueTooLarge,InvalidQueueAlignment,DescriptorIndexOutOfBounds,DescriptorLengthZero,QueueNotReady,DescriptorCycle,DescriptorChainTooLong,QueueFull,InvalidQueueIndex}
#[repr(C)]#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioDescriptor{pub addr:u64,pub len:u32,pub flags:u16,pub next:u16}
impl VirtioDescriptor{pub const fn validate(&self,queue_size:u16)->Result<(),VirtioError>{if self.len==0{return Err(VirtioError::DescriptorLengthZero)}if self.next>=queue_size{return Err(VirtioError::DescriptorIndexOutOfBounds)}Ok(())}}
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioQueueConfig{pub size:u16,pub alignment:u16}
impl VirtioQueueConfig{pub const fn validate(self,max:u16)->Result<(),VirtioError>{if self.size==0{return Err(VirtioError::QueueCountZero)}if self.size>max{return Err(VirtioError::QueueTooLarge)}if self.alignment==0||!self.alignment.is_power_of_two(){return Err(VirtioError::InvalidQueueAlignment)}Ok(())}}

pub struct VirtioSplitQueue<const N:usize>{descriptors:[Option<VirtioDescriptor>;N],available:[u16;N],used:[u16;N],avail_idx:u16,used_idx:u16}
impl<const N:usize> VirtioSplitQueue<N>{pub const fn new()->Self{Self{descriptors:[None;N],available:[0;N],used:[0;N],avail_idx:0,used_idx:0}}pub const fn capacity(&self)->u16{N as u16}pub fn enqueue(&mut self,index:u16,descriptor:VirtioDescriptor)->Result<(),VirtioError>{if N==0||index>=N as u16{return Err(VirtioError::InvalidQueueIndex)}if self.avail_idx.wrapping_sub(self.used_idx)>=N as u16{return Err(VirtioError::QueueFull)}descriptor.validate(N as u16)?;self.descriptors[index as usize]=Some(descriptor);self.available[(self.avail_idx as usize)%N]=index;self.avail_idx=self.avail_idx.wrapping_add(1);Ok(())}pub fn pop_available(&mut self)->Result<Option<VirtioDescriptor>,VirtioError>{if self.avail_idx==self.used_idx{return Ok(None)}let slot=(self.used_idx as usize)%N;let index=self.available[slot];let d=self.descriptors[index as usize].ok_or(VirtioError::InvalidQueueIndex)?;self.used[slot]=index;self.used_idx=self.used_idx.wrapping_add(1);Ok(Some(d))}pub const fn available_count(&self)->u16{self.avail_idx.wrapping_sub(self.used_idx)}}

pub fn validate_chain<const N:usize>(descriptors:&[Option<VirtioDescriptor>;N],head:u16)->Result<usize,VirtioError>{if N==0||head>=N as u16{return Err(VirtioError::InvalidQueueIndex)}let mut current=head;let mut count=0usize;while count<N{let d=match descriptors[current as usize]{Some(v)=>v,None=>return Err(VirtioError::InvalidQueueIndex)};d.validate(N as u16)?;count+=1;if d.flags&DESC_NEXT==0{return Ok(count)}current=d.next;if current>=N as u16{return Err(VirtioError::DescriptorIndexOutOfBounds)}}Err(VirtioError::DescriptorCycle)}

pub struct VirtioDevice{negotiated:VirtioFeatures,ready:bool,queue_count:u16}
impl VirtioDevice{pub const fn new()->Self{Self{negotiated:VirtioFeatures(0),ready:false,queue_count:0}}pub const fn negotiate(d:VirtioFeatures,r:VirtioFeatures)->VirtioFeatures{d.intersection(r)}pub fn initialize(&mut self,d:VirtioFeatures,r:VirtioFeatures)->Result<(),VirtioError>{if self.ready{return Err(VirtioError::AlreadyReady)}let n=Self::negotiate(d,r);if !n.contains(VirtioFeatures::VERSION_1){return Err(VirtioError::MissingVersion)}self.negotiated=n;Ok(())}pub fn configure_queues(&mut self,q:&[VirtioQueueConfig],max:u16)->Result<(),VirtioError>{if !self.negotiated.contains(VirtioFeatures::VERSION_1){return Err(VirtioError::MissingVersion)}if q.is_empty(){return Err(VirtioError::QueueCountZero)}for x in q.iter().copied(){x.validate(max)?}self.queue_count=q.len() as u16;self.ready=true;Ok(())}pub fn validate_descriptor(&self,d:&VirtioDescriptor)->Result<(),VirtioError>{if !self.ready{return Err(VirtioError::QueueNotReady)}d.validate(self.queue_count.max(1))}pub const fn is_ready(&self)->bool{self.ready}pub const fn features(&self)->VirtioFeatures{self.negotiated}pub const fn queue_count(&self)->u16{self.queue_count}}

#[cfg(test)]mod tests{use super::*;
#[test]fn negotiation_requires_common_features(){let h=VirtioFeatures((1<<32)|(1<<29));let g=VirtioFeatures((1<<32)|(1<<28));let mut d=VirtioDevice::new();d.initialize(h,g).unwrap();assert!(d.features().contains(VirtioFeatures::VERSION_1));}
#[test]fn valid_queue_configuration_makes_ready(){let mut d=VirtioDevice::new();d.initialize(VirtioFeatures::VERSION_1,VirtioFeatures::VERSION_1).unwrap();d.configure_queues(&[VirtioQueueConfig{size:64,alignment:4096}],64).unwrap();assert!(d.is_ready());}
#[test]fn split_queue_round_trip(){let mut q:VirtioSplitQueue<4>=VirtioSplitQueue::new();q.enqueue(0,VirtioDescriptor{addr:0x1000,len:4,flags:0,next:0}).unwrap();assert_eq!(q.available_count(),1);assert_eq!(q.pop_available().unwrap().unwrap().addr,0x1000);assert_eq!(q.available_count(),0);}
#[test]fn chain_is_validated(){let a=Some(VirtioDescriptor{addr:0x1000,len:4,flags:DESC_NEXT,next:1});let b=Some(VirtioDescriptor{addr:0x2000,len:4,flags:0,next:0});assert_eq!(validate_chain(&[a,b],0).unwrap(),2);}
#[test]fn chain_cycle_is_rejected(){let a=Some(VirtioDescriptor{addr:0x1000,len:4,flags:DESC_NEXT,next:1});let b=Some(VirtioDescriptor{addr:0x2000,len:4,flags:DESC_NEXT,next:0});assert_eq!(validate_chain(&[a,b],0),Err(VirtioError::DescriptorCycle));}
#[test]fn queue_full_is_rejected(){let mut q:VirtioSplitQueue<2>=VirtioSplitQueue::new();let d=VirtioDescriptor{addr:1,len:1,flags:0,next:0};q.enqueue(0,d).unwrap();q.enqueue(1,d).unwrap();assert_eq!(q.enqueue(0,d),Err(VirtioError::QueueFull));}
#[test]fn invalid_descriptor_is_rejected(){let mut d=VirtioDevice::new();d.initialize(VirtioFeatures::VERSION_1,VirtioFeatures::VERSION_1).unwrap();d.configure_queues(&[VirtioQueueConfig{size:64,alignment:4096}],64).unwrap();assert_eq!(d.validate_descriptor(&VirtioDescriptor{addr:0x1000,len:0,flags:0,next:0}),Err(VirtioError::DescriptorLengthZero));}
}