#![no_std]

#[repr(transparent)]#[derive(Clone,Copy,PartialEq,Eq)]pub struct VirtioFeatures(pub u64);
impl VirtioFeatures{pub const VERSION_1:Self=Self(1<<32);pub const ACCESS_PLATFORM:Self=Self(1<<33);pub const RING_INDIRECT_DESC:Self=Self(1<<28);pub const RING_EVENT_IDX:Self=Self(1<<29);pub const RING_PACKED:Self=Self(1<<34);pub const fn contains(self,o:Self)->bool{(self.0&o.0)==o.0}pub const fn intersection(self,o:Self)->Self{Self(self.0&o.0)}}
pub const DESC_NEXT:u16=1;pub const DESC_WRITE:u16=2;pub const DESC_INDIRECT:u16=4;
pub const MMIO_MAGIC:u32=0x7472_6976;pub const MMIO_VERSION:u32=2;pub const MMIO_STATUS:u64=0x070;pub const MMIO_QUEUE_NOTIFY:u64=0x050;pub const MMIO_INTERRUPT_STATUS:u64=0x060;pub const MMIO_INTERRUPT_ACK:u64=0x064;
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub enum VirtioError{MissingVersion,AlreadyReady,QueueCountZero,QueueTooLarge,InvalidQueueAlignment,DescriptorIndexOutOfBounds,DescriptorLengthZero,QueueNotReady,DescriptorCycle,QueueFull,InvalidQueueIndex,CompletionQueueFull,NoCompletion,InvalidStatus,TransportFault,QueueNotConfigured,BadMmioOffset,InvalidMmioWrite,InterruptNotPending,QueueNotifiedBeforeReady}
#[repr(u8)]#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub enum VirtioStatus{Reset=0,Acknowledge=1,Driver=2,DriverOk=4,FeaturesOk=8,Failed=128}
impl VirtioStatus{pub const fn has(self,f:u8)->bool{(self as u8&f)==f}}
#[repr(C)]#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioMmioRegisters{pub magic:u32,pub version:u32,pub device_id:u32,pub vendor_id:u32,pub device_features:u64,pub driver_features:u64,pub status:u8,pub queue_count:u16,pub queue_notify:u16,pub interrupt_status:u32,pub interrupt_ack:u32}
impl VirtioMmioRegisters{pub const fn new(device_id:u32,vendor_id:u32,features:VirtioFeatures)->Self{Self{magic:MMIO_MAGIC,version:MMIO_VERSION,device_id,vendor_id,device_features:features.0,driver_features:0,status:0,queue_count:0,queue_notify:u16::MAX,interrupt_status:0,interrupt_ack:0}}pub const fn valid_identity(&self)->bool{self.magic==MMIO_MAGIC&&self.version==MMIO_VERSION&&self.device_id!=0&&self.vendor_id!=0}pub fn write(&mut self,offset:u64,value:u32)->Result<(),VirtioError>{match offset{MMIO_STATUS=>{self.status=(value&0xff)as u8;Ok(())},MMIO_QUEUE_NOTIFY=>{if value>u16::MAX as u32{return Err(VirtioError::InvalidMmioWrite)}self.queue_notify=value as u16;Ok(())},MMIO_INTERRUPT_ACK=>{self.interrupt_ack=value;self.interrupt_status&=!value;Ok(())},_=>Err(VirtioError::BadMmioOffset)}}pub const fn read(&self,offset:u64)->Result<u32,VirtioError>{match offset{MMIO_STATUS=>Ok(self.status as u32),MMIO_QUEUE_NOTIFY=>Ok(self.queue_notify as u32),MMIO_INTERRUPT_STATUS=>Ok(self.interrupt_status),MMIO_INTERRUPT_ACK=>Ok(self.interrupt_ack),_=>Err(VirtioError::BadMmioOffset)}}pub fn raise_interrupt(&mut self,bits:u32){self.interrupt_status|=bits}pub fn clear_interrupt(&mut self,bits:u32){self.interrupt_status&=!bits}}
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioTransportState{status:u8,device_features:VirtioFeatures,driver_features:VirtioFeatures,queue_count:u16,notified_queue:u16}
impl VirtioTransportState{pub const fn new(features:VirtioFeatures)->Self{Self{status:0,device_features:features,driver_features:VirtioFeatures(0),queue_count:0,notified_queue:u16::MAX}}pub fn acknowledge(&mut self)->Result<(),VirtioError>{if self.status!=0{return Err(VirtioError::InvalidStatus)}self.status=VirtioStatus::Acknowledge as u8;Ok(())}pub fn set_driver(&mut self)->Result<(),VirtioError>{if !VirtioStatus::has(VirtioStatus::Acknowledge,self.status){return Err(VirtioError::InvalidStatus)}self.status|=VirtioStatus::Driver as u8;Ok(())}pub fn negotiate(&mut self,driver:VirtioFeatures)->Result<VirtioFeatures,VirtioError>{if !VirtioStatus::has(VirtioStatus::Driver,self.status){return Err(VirtioError::InvalidStatus)}let n=self.device_features.intersection(driver);if !n.contains(VirtioFeatures::VERSION_1){self.status|=VirtioStatus::Failed as u8;return Err(VirtioError::MissingVersion)}self.driver_features=n;self.status|=VirtioStatus::FeaturesOk as u8;Ok(n)}pub fn configure_queues(&mut self,count:u16)->Result<(),VirtioError>{if count==0||!VirtioStatus::has(VirtioStatus::FeaturesOk,self.status){return Err(VirtioError::QueueNotConfigured)}self.queue_count=count;Ok(())}pub fn driver_ok(&mut self)->Result<(),VirtioError>{if self.queue_count==0||!VirtioStatus::has(VirtioStatus::FeaturesOk,self.status){return Err(VirtioError::QueueNotConfigured)}self.status|=VirtioStatus::DriverOk as u8;Ok(())}pub fn notify_queue(&mut self,index:u16)->Result<(),VirtioError>{if !VirtioStatus::has(VirtioStatus::DriverOk,self.status){return Err(VirtioError::InvalidStatus)}if index>=self.queue_count{return Err(VirtioError::InvalidQueueIndex)}self.notified_queue=index;Ok(())}pub const fn status(&self)->u8{self.status}pub const fn notified_queue(&self)->u16{self.notified_queue}pub const fn negotiated_features(&self)->VirtioFeatures{self.driver_features}}
#[repr(C)]#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioDescriptor{pub addr:u64,pub len:u32,pub flags:u16,pub next:u16}
impl VirtioDescriptor{pub const fn validate(&self,queue_size:u16)->Result<(),VirtioError>{if self.len==0{return Err(VirtioError::DescriptorLengthZero)}if self.next>=queue_size{return Err(VirtioError::DescriptorIndexOutOfBounds)}Ok(())}}
#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioQueueConfig{pub size:u16,pub alignment:u16}
impl VirtioQueueConfig{pub const fn validate(self,max:u16)->Result<(),VirtioError>{if self.size==0{return Err(VirtioError::QueueCountZero)}if self.size>max{return Err(VirtioError::QueueTooLarge)}if self.alignment==0||!self.alignment.is_power_of_two(){return Err(VirtioError::InvalidQueueAlignment)}Ok(())}}
#[repr(C)]#[derive(Clone,Copy,PartialEq,Eq,Debug)]pub struct VirtioUsedElem{pub id:u16,pub len:u32}
pub struct VirtioSplitQueue<const N:usize>{descriptors:[Option<VirtioDescriptor>;N],available:[u16;N],used:[VirtioUsedElem;N],avail_idx:u16,used_idx:u16,device_avail_idx:u16,device_used_idx:u16}
impl<const N:usize>VirtioSplitQueue<N>{pub const fn new()->Self{Self{descriptors:[None;N],available:[0;N],used:[VirtioUsedElem{id:0,len:0};N],avail_idx:0,used_idx:0,device_avail_idx:0,device_used_idx:0}}pub fn enqueue(&mut self,index:u16,descriptor:VirtioDescriptor)->Result<(),VirtioError>{if N==0||index>=N as u16{return Err(VirtioError::InvalidQueueIndex)}if self.avail_idx.wrapping_sub(self.used_idx)>=N as u16{return Err(VirtioError::QueueFull)}descriptor.validate(N as u16)?;self.descriptors[index as usize]=Some(descriptor);self.available[(self.avail_idx as usize)%N]=index;self.avail_idx=self.avail_idx.wrapping_add(1);Ok(())}pub fn pop_available(&mut self)->Result<Option<(u16,VirtioDescriptor)>,VirtioError>{if self.avail_idx==self.device_avail_idx{return Ok(None)}let slot=(self.device_avail_idx as usize)%N;let index=self.available[slot];let d=self.descriptors[index as usize].ok_or(VirtioError::InvalidQueueIndex)?;self.device_avail_idx=self.device_avail_idx.wrapping_add(1);Ok(Some((index,d)))}pub fn complete(&mut self,index:u16,len:u32)->Result<(),VirtioError>{if self.used_idx.wrapping_sub(self.device_used_idx)>=N as u16{return Err(VirtioError::CompletionQueueFull)}if index>=N as u16{return Err(VirtioError::InvalidQueueIndex)}self.used[(self.used_idx as usize)%N]=VirtioUsedElem{id:index,len};self.used_idx=self.used_idx.wrapping_add(1);Ok(())}pub fn pop_completion(&mut self)->Result<Option<VirtioUsedElem>,VirtioError>{if self.used_idx==self.device_used_idx{return Ok(None)}let slot=(self.device_used_idx as usize)%N;let e=self.used[slot];self.device_used_idx=self.device_used_idx.wrapping_add(1);Ok(Some(e))}}
pub fn validate_chain<const N:usize>(descriptors:&[Option<VirtioDescriptor>;N],head:u16)->Result<usize,VirtioError>{if N==0||head>=N as u16{return Err(VirtioError::InvalidQueueIndex)}let mut current=head;let mut count=0usize;while count<N{let d=match descriptors[current as usize]{Some(v)=>v,None=>return Err(VirtioError::InvalidQueueIndex)};d.validate(N as u16)?;count+=1;if d.flags&DESC_NEXT==0{return Ok(count)}current=d.next;if current>=N as u16{return Err(VirtioError::DescriptorIndexOutOfBounds)}}Err(VirtioError::DescriptorCycle)}
#[cfg(test)]mod tests{use super::*;#[test]fn mmio_identity_is_valid(){assert!(VirtioMmioRegisters::new(2,0x1234,VirtioFeatures::VERSION_1).valid_identity())}#[test]fn irq_bits_can_be_raised_and_cleared(){let mut r=VirtioMmioRegisters::new(2,0x1234,VirtioFeatures::VERSION_1);r.raise_interrupt(3);assert_eq!(r.read(MMIO_INTERRUPT_STATUS).unwrap(),3);r.clear_interrupt(1);assert_eq!(r.read(MMIO_INTERRUPT_STATUS).unwrap(),2)}#[test]fn transport_reaches_driver_ok(){let mut t=VirtioTransportState::new(VirtioFeatures::VERSION_1);t.acknowledge().unwrap();t.set_driver().unwrap();t.negotiate(VirtioFeatures::VERSION_1).unwrap();t.configure_queues(2).unwrap();t.driver_ok().unwrap();assert_eq!(t.status(),15)}#[test]fn queue_completion_round_trip(){let mut q:VirtioSplitQueue<4>=VirtioSplitQueue::new();q.enqueue(0,VirtioDescriptor{addr:0x1000,len:16,flags:0,next:0}).unwrap();let(id,d)=q.pop_available().unwrap().unwrap();q.complete(id,d.len).unwrap();assert_eq!(q.pop_completion().unwrap().unwrap().len,16)}#[test]fn chain_cycle_rejected(){let a=Some(VirtioDescriptor{addr:1,len:1,flags:DESC_NEXT,next:1});let b=Some(VirtioDescriptor{addr:2,len:1,flags:DESC_NEXT,next:0});assert_eq!(validate_chain(&[a,b],0),Err(VirtioError::DescriptorCycle))}}
