#![no_std]
use super::core::{AdapterState,CoreError,DriverAdapter,DriverSlot,HardwareAbstraction,HardwareInfo,WindowsDriverAdapter};
use super::universal::{DriverAbi,DriverOs};
pub struct WindowsLayer<A>{pub slot:DriverSlot<A>}
impl<A:WindowsDriverAdapter>WindowsLayer<A>{
 pub const fn new(adapter:A)->Self{Self{slot:DriverSlot::new(adapter)}}
 pub fn validate(&self,hw:&HardwareInfo)->Result<(),CoreError>{let id=self.slot.adapter.identity();if id.os!=DriverOs::Windows||id.abi!=DriverAbi::WindowsCompat{return Err(CoreError::UnsupportedAbi)}let api=self.slot.adapter.windows_api_version();if id.api_version==0||api==0||api>u32::from(u16::MAX)||id.api_version!=api as u16{return Err(CoreError::InvalidRequest)}let name=self.slot.adapter.windows_driver_name();if name.len()<3||!name.as_bytes().iter().any(|b|*b==b'-'){return Err(CoreError::InvalidRequest)}if !id.matches(hw)||!hw.valid()||hw.irq==u32::MAX{return Err(CoreError::InvalidDevice)}Ok(())}
 pub fn can_probe(&self,hw:&HardwareInfo)->bool{self.validate(hw).is_ok()&&self.slot.state==AdapterState::New}
 pub fn probe(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{self.validate(hw)?;if self.slot.state!=AdapterState::New{return Err(CoreError::NotBound)}self.slot.adapter.probe(hw).map_err(|_|CoreError::ProbeFailed)?;self.slot.state=AdapterState::Probed;Ok(())}
 pub fn start(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{self.validate(hw)?;if self.slot.state!=AdapterState::Probed&&self.slot.state!=AdapterState::Stopped{return Err(CoreError::NotBound)}self.slot.adapter.start(hw).map_err(|_|CoreError::StartFailed)?;self.slot.state=AdapterState::Running;Ok(())}
 pub fn stop(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.adapter.stop(hw).map_err(|_|CoreError::PolicyDenied)?;self.slot.state=AdapterState::Stopped;Ok(())}
 pub fn remove(&mut self,hw:&HardwareInfo)->Result<(),CoreError>{if self.slot.state==AdapterState::Running{return Err(CoreError::PolicyDenied)}if self.slot.state==AdapterState::Removed{return Err(CoreError::NotBound)}self.slot.adapter.remove(hw).map_err(|_|CoreError::PolicyDenied)?;self.slot.state=AdapterState::Removed;Ok(())}
 pub fn mmio_read32<H:HardwareAbstraction>(&self,hw:&HardwareInfo,hal:&H,offset:u64)->Result<u32,CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.mmio_read32(hw,hal,offset)}
 pub fn mmio_write32<H:HardwareAbstraction>(&self,hw:&HardwareInfo,hal:&mut H,offset:u64,value:u32)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.mmio_write32(hw,hal,offset,value)}
 pub fn irq_ack<H:HardwareAbstraction>(&self,hw:&HardwareInfo,hal:&mut H)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.irq_ack(hw,hal)}
 pub fn dma_submit<H:HardwareAbstraction>(&self,hw:&HardwareInfo,hal:&mut H,bytes:u64,address_bits:u8)->Result<(),CoreError>{if self.slot.state!=AdapterState::Running{return Err(CoreError::NotBound)}self.slot.dma_submit(hw,hal,bytes,address_bits)}
}
#[cfg(test)]mod tests{use super::*;use super::super::bus::DeviceId;struct Mock{api:u32,name:&'static str,os:DriverOs,abi:DriverAbi,vendor:u16,device:u16,signed:bool,fail_probe:bool,fail_start:bool}impl DriverAdapter for Mock{fn identity(&self)->super::super::core::DriverIdentity{super::super::core::DriverIdentity{os:self.os,abi:self.abi,api_version:self.api as u16,vendor:self.vendor,device:self.device,signed:self.signed}}fn probe(&mut self,_:&HardwareInfo)->Result<(),CoreError>{if self.fail_probe{Err(CoreError::ProbeFailed)}else{Ok(())}}fn start(&mut self,_:&HardwareInfo)->Result<(),CoreError>{if self.fail_start{Err(CoreError::StartFailed)}else{Ok(())}}fn stop(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}fn remove(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}}impl WindowsDriverAdapter for Mock{fn windows_api_version(&self)->u32{self.api}fn windows_driver_name(&self)->&'static str{self.name}}struct Hal;impl HardwareAbstraction for Hal{fn mmio_read32(&self,_:&HardwareInfo,o:u64)->Result<u32,CoreError>{Ok(o as u32)}fn mmio_write32(&mut self,_:&HardwareInfo,_:u64,_:u32)->Result<(),CoreError>{Ok(())}fn irq_ack(&mut self,_:&HardwareInfo)->Result<(),CoreError>{Ok(())}fn dma_submit(&mut self,_:&HardwareInfo,_:u64)->Result<(),CoreError>{Ok(())}}fn hw()->HardwareInfo{HardwareInfo{id:DeviceId{vendor:1,device:2,class:0,revision:1},mmio_base:0x1000,mmio_length:0x100,irq:5,dma_bits:64}}fn good()->WindowsLayer<Mock>{WindowsLayer::new(Mock{api:7,name:"awe-wdm",os:DriverOs::Windows,abi:DriverAbi::WindowsCompat,vendor:1,device:2,signed:true,fail_probe:false,fail_start:false})}#[test]fn full_lifecycle_and_io(){let mut x=good();x.probe(&hw()).unwrap();x.start(&hw()).unwrap();let h=Hal;assert_eq!(x.mmio_read32(&hw(),&h,4),Ok(4));x.stop(&hw()).unwrap();x.remove(&hw()).unwrap();assert_eq!(x.slot.state,AdapterState::Removed)}}